version: '2.1'

services:
    db:
      image: postgres
      healthcheck:
        test: exit 0
      ports:
      - 5432:5432
      environment:
        - POSTGRES_DB=students_db
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
      volumes:    # will let you start up an initial database with an sql file in the area
          - ./studentDBinit.sql:/docker-entrypoint-initdb.d/studentDBinit.sql

    server:
      build: .
      command: npm run serverStart
      image: willjantscher/students_server:latest #make sure to include this!
      environment:
        - DATABASE_URL=postgres://admin:admin@db:5432
        - NODE_ENV=test
      depends_on:
        db:
          condition: service_healthy
      links:
        - db
      ports:
        - 6003:6004   #server should mount on port 6003

    # app:
    #   build: .
    #   command: npm start
    #   depends_on: 
    #     - server
    #   links:
    #     - server
    #   ports:
    #     - 3001:3003



    